# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration:
        - Release_mkl
        - Release_openblas
        - Release_openblas_noavx
        - Release_cuda102_cudnn76_tr72_sm61_75
        - Release_cuda118_cudnn86_tr85_sm86_89
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c ${{ matrix.configuration }} -o SelectAndSearch\bin\Release\net7.0-windows\win-x64\publish
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SelectAndSearch_${{ matrix.configuration }}
        path: SelectAndSearch\bin\Release\net7.0-windows\win-x64\publish
  benchmark:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
        - Release_mkl
        - Release_openblas
        - Release_openblas_noavx

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Benchmark ${{ matrix.configuration }}
      run: dotnet run --project .\SelectAndSearch.Benchmark\SelectAndSearch.Benchmark.csproj -c ${{ matrix.configuration }}
